agentName: android
agentType: integration
title: 'Getting started with android agent'
metaDescription: 'Install the Streaming video & ads for android agent'
introFilePath: 'src/install/android/intro.mdx'

appInfo: 
  - optionType: deployment
    label: ''
    placeholder: 'Choose an option'
    options: 
      - value: 'EU1'
        displayName: 'Instrument a new mobile application'
      - value: 'EA2'
        displayName: 'Instrument on mobile application you are already monitoring'
steps:
  - filePath: 'src/install/android/android-path/install_the_app.mdx'
  - filePath: 'src/install/android/android-path/select_account.mdx'
  - filePath: 'src/install/android/android-path/select_application.mdx'
  - filePath: 'src/install/android/android-path/select_android.mdx'
  - filePath: 'src/install/android/appInfo.mdx'
  - filePath: 'src/install/android/android-path/appInfo_EU1.mdx'
    overrides:
      - isConditionalStep: true      
        selectedOptions:
          - optionType: deployemnt
            options:
              - value: 'EU1'
  - filePath: 'src/install/android/appInfo_EA2.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'EA2'                                             
whatsNextFilePath: 'src/install/android/whatsNext.mdx'