agentName: browser-media
agentType: integration
title: 'Getting started with browser agent'
metaDescription: 'Install the Streaming video & ads for browser agent'
introFilePath: 'src/install/browser-media/intro.mdx'

appInfo: 
  - optionType: task
    label: ''
    placeholder: 'Choose an option'
    options: 
      - value: 'newapplication'
        displayName: 'Install browser agent for new application'
      - value: 'EU2'
        displayName: 'Install browser agent for existing application'
steps:
  - filePath: 'src/install/browser-media/browser-path/install_the_app.mdx'
  - filePath: 'src/install/browser-media/browser-path/select_account.mdx'
  - filePath: 'src/install/browser-media/browser-path/select_application.mdx'
  - filePath: '/src/install/browser-media/appInfo.mdx'
  - filePath: 'src/install/browser-media/browser-path/newapplication.mdx'
    overrides:
      - isConditionalStep: true      
        selectedOptions:
          - optionType: task
            options:
              - value: 'newapplication'
  - filePath: 'src/install/browser-media/appInfo_EU2.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: task
            options:
              - value: 'EU2'                                             
whatsNextFilePath: 'src/install/browser-media/whatsNext.mdx'