agentName: browser-media
agentType: integration
title: 'Getting started with browser agent'
metaDescription: 'Install the Streaming video & ads for browser agent'
introFilePath: 'src/install/browser-media/intro.mdx'
appInfo: 
  - optionType: service
    label: ''
    placeholder: 'Select any one of the following options to install the browser agent to the application'
    options: 
      - value: 'NU2'
        displayName: 'Install browser agent for new application'
      - value: 'EU2'
        displayName: 'Install browser agent for existing application'    
steps:
  - filePath: 'src/install/browser-media/appInfo_service.mdx'
  - filePath: 'src/install/browser-media/appInfo_NU2.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: service
            options:
              - value: 'NU2'
  - filePath: 'src/install/browser-media/appInfo_NU2.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: service
            options:
              - value: 'EU2'                                             
