agentName: ios-media
agentType: integration
title: 'Getting started with iOS agent'
metaDescription: 'Install the Streaming video & ads for iOS agent'
introFilePath: 'src/install/ios-media/intro.mdx'
appInfo: 
  - optionType: task
    label: ''
    placeholder: 'Choose an option'
    options: 
      - value: 'AD'
        displayName: 'Instrument a new mobile application'
      - value: 'EI2'
        displayName: 'Instrument on mobile application you are already monitoring'

steps:
  - filePath: 'src/install/ios-media/ios-path/install_the_app.mdx'
  - filePath: 'src/install/ios-media/ios-path/select_account.mdx'
  - filePath: 'src/install/ios-media/ios-path/select_application.mdx'
  - filePath: 'src/install/ios-media/ios-path/select_ios.mdx'
  - filePath: 'src/install/ios-media/appInfo.mdx'
  - filePath: 'src/install/ios-media/ios-path/appInfo_AD.mdx'
    overrides:
      - isConditionalStep: true      
        selectedOptions:
          - optionType: task
            options:
              - value: 'AD'
  - filePath: 'src/install/ios-media/appInfo_EI2.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: task
            options:
              - value: 'EI2'                                             
whatsNextFilePath: 'src/install/ios-media/whatsNext.mdx'